name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build binary and Node.js ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20]
    runs-on: ubuntu-latest
    container: centos/python-38-centos7:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js  ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install
        run: npm install

      - name: Pack
        run: npm run binary:pack

      - name: Release
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
        run: npm run binary:release